function create_solution_space_GUI(dataManager)
% CREATE_SOLUTION_SPACE_GUI Generates an interactive GUI for solution space control.
%   CREATE_SOLUTION_SPACE_GUI(DATA_MANAGER) creates a graphical interface 
%   using MATLAB's UI components to explore and configure design variables, 
%   quantities of interest (QoIs), and related parameters within a project.
%
%   INPUT:
%       dataManager - Struct or class instance containing parsed design data
%           from Excel or other sources. Expected fields include:
%               - x: struct of design variables with fields (val, min, max, fixed)
%               - param: struct of fixed design parameters
%               - qoi: struct of quantities of interest or constraints
%
%   FUNCTIONALITY:
%       - Tabs for each design variable with sliders, bounds, and fixed flags
%       - Panels for quantity of interest visualization and parameter inspection
%       - Dynamic update of fields on user interaction
%       - Input validation to ensure consistency
%
%   COMPONENTS:
%       - uifigure: Main GUI window
%       - uitabgroup, uitab: Organizes controls for variables and data
%       - uislider, uieditfield, uicheckbox: Interactive components
%       - uigridlayout, uipanel, uilabel: Layout and display management
%
%   OUTPUT:
%       None (GUI is displayed for user interaction)
%
%   DEPENDENCIES:
%       Assumes dataManager is preloaded with structured data using a
%       compatible Excel parser or similar data ingestion function.
%
%   Copyright 2025 Eduardo Rodrigues Della Noce (Supervisor)
%   Copyright 2025 Ali Abbas Kapadia (Main Author)
%   SPDX-License-Identifier: Apache-2.0

    %% Create GUI layout

    % Retrive Screen size
    screenSize = get(0, 'ScreenSize');

    % Define GUI Screen
    hFig = uifigure('Name', 'Solution Space GUI', 'NumberTitle', 'off');
    hFig.Position = [screenSize(1), screenSize(2)+10, screenSize(3), screenSize(4)-10]; % Set the figure to full screen
    hFig.WindowState = 'maximized';

    %% Prepare a GUI %%
    % Define Tabs to be added to the screen
    tabGroup = uitabgroup('Parent', hFig, 'Units', 'normalized',...
                        'Position',[.020 .15 0.4 .8]);
    tab1 = uitab(tabGroup,"Title","Design Variable");
    tab4 = uitab(tabGroup,"Title","Quantaties of Interest");
    tab2 = uitab(tabGroup,"Title","Values from Plot");
    tab3 = uitab(tabGroup,"Title","PostProcessing");

    %% 1. Tab for Design variables %%
    % Create a main panel for the sliders and inputs
    designVariablePanel = uipanel('Parent', tab1, 'Title', 'Design Variables', ...
                            'Units', 'pixels',...
                            'Position', [14.6000   14.4000  516.8000  509.2000],...
                            'Scrollable','on');

    % Sliders and textboxes for each design variable
    nVariables = numel(dataManager.DesignVariables);                       % Number of design variables
    dataManager.SliderHandles = gobjects(nVariables, 2);                    % Store slider handles for lower and upper bounds
    dataManager.TextHandles = gobjects(nVariables, 2);                      % Store text box handles for lower and upper values

    % Calculate the initialization of Panel
    designVariablePanelLeft = 11.2800;
    designVariablePanelWidth = 485;
    designVariablePanelHeight = 140;
    designPanelGap = 10;
    topMargin = 20;
    bottomMargin = 10;

    % Total required scroll height
    scrollContentHeight = nVariables * (designVariablePanelHeight + designPanelGap) + topMargin + bottomMargin;

    for variableIteration = 1:nVariables
        bottom = scrollContentHeight - variableIteration*(designVariablePanelHeight + designPanelGap);  % count from top down

        % Create a panel for each variable
        variablePanel(variableIteration) = uipanel('Parent', designVariablePanel, 'Title',...
            dataManager.DesignVariables(variableIteration).dispname, ...
            'Units', 'pixels', ...
            'Position', [designVariablePanelLeft, bottom, designVariablePanelWidth, designVariablePanelHeight]);

        % Design Space Lower Bound
        dataManager.TextHandles.DesignLimits(variableIteration, 1) = uicontrol('Parent', variablePanel(variableIteration),...
            'Style', 'edit', ...
            'String', num2str(dataManager.DesignVariables(variableIteration).dslb, '%.2f'), ...
            'Units', 'pixels', ...
            'Position', [6.5000, 42.0392, 39.0048, 36.0344], ...
            'FontSize', 9, 'ForegroundColor', 'red', ...
            'Callback', @(src, event) design_textbox_callback(src, dataManager, variableIteration, 1));

        % Solution Space Lower Bound
        dataManager.TextHandles.DesignBox(variableIteration, 1) = uicontrol('Parent', variablePanel(variableIteration),...
             'Style', 'edit', ...
             'String', num2str(dataManager.DesignVariables(variableIteration).sblb, '%.2f'), ...
             'Units', 'pixels', ...
             'Position', [50.5000, 42.0392, 39.0048, 36.0344], ...
             'Callback', @(src, event) textbox_callback(dataManager, variableIteration, 1));

        % Create the slider with adjusted position
        dataManager.SliderHandles(variableIteration) = uislider(variablePanel(variableIteration),...
            'range', ...
            'Limits', [dataManager.DesignVariables(variableIteration).dslb dataManager.DesignVariables(variableIteration).dsub], ...
            'Value', [dataManager.DesignVariables(variableIteration).sblb dataManager.DesignVariables(variableIteration).sbub], ...
            'MinorTicks', [], ...
            'Position', [105.5000, 55.000, 273.5000, 3.0000],...
            'ValueChangedFcn', @(src, event) slider_callback(dataManager, variableIteration));

        % Solution Space Upper Bound
        dataManager.TextHandles.DesignBox(variableIteration, 2) = uicontrol('Parent', variablePanel(variableIteration),...
            'Style', 'edit', ...
            'String', num2str(dataManager.DesignVariables(variableIteration).sbub, '%.2f'), ...
            'Units', 'pixels', ...
            'Position', [394.5000, 42.0392, 40.0049, 36.0344], ...
            'Callback', @(src, event) textbox_callback(dataManager, variableIteration, 2));

        % Design Space Upper Bound (rightmost)
        dataManager.TextHandles.DesignLimits(variableIteration, 2) = uicontrol('Parent', variablePanel(variableIteration),...
            'Style', 'edit', ...
            'String', num2str(dataManager.DesignVariables(variableIteration).dsub, '%.2f'), ...
            'Units', 'pixels', ...
            'Position', [439.5000, 42.0392, 39.0048, 36.0344], ...
            'FontSize', 9, 'ForegroundColor', 'red', ...
            'Callback', @(src, event) design_textbox_callback(src, dataManager, variableIteration, 2));
    end

    scroll(designVariablePanel,'top','right')

    %% 2. Tab for QoI %%
    quantatiesOfInterestPanel = uipanel('Parent', tab4, 'Title', 'Quantaties of Interest',...
        'Units', 'pixels',...
        'Position', [14.6000   14.4000  516.8000  509.2000],...
        'Scrollable','on');

    % Sliders and textboxes for each design variable
    nQuantatiesOfInterest = numel(dataManager.QuantatiesOfInterests);                                        % Number of design variables
    checkHandles = gobjects(nQuantatiesOfInterest, 1);                                        % Store active status
    dataManager.QOITextHandles = gobjects(nQuantatiesOfInterest, 2);                        % Store text box handles for lower and upper values

    for variableIteration = 1:nQuantatiesOfInterest
        bottom = scrollContentHeight - variableIteration*(designVariablePanelHeight + designPanelGap);  % count from top down

        % Create a panel for each variable
        quantatiesOfInterestBlock = uipanel('Parent', quantatiesOfInterestPanel,...
            'Title', dataManager.QuantatiesOfInterests(variableIteration).dispname, ...
            'Units', 'pixels', ...
            'Position', [designVariablePanelLeft, bottom, designVariablePanelWidth, designVariablePanelHeight]);
    
        % Label for 'InActive'
        uicontrol('Parent', quantatiesOfInterestBlock, 'Style', 'text', 'String', 'InActive', ...
                  'Units', 'pixels', 'Position', [5.9200, 65.5000, 73.8000, 35.400], ...
                  'HorizontalAlignment', 'center');
    
        % Checkbox for 'InActive'
        checkHandles(variableIteration) = uicontrol('Parent', quantatiesOfInterestBlock, ...
                        'Style', 'checkbox', ...
                        'Units', 'pixels', ...
                        'Position', [34.0000, 55.0000, 20.0000, 20.0000], ...
                        'FontSize', 10, ...
                        'Callback', @(hObject, ~) toggle_textbox(hObject, dataManager, variableIteration));
    
        % Label for 'Lower Bound'
        uicontrol('Parent', quantatiesOfInterestBlock, 'Style', 'text', 'String', 'Lower Bound', ...
                  'Units', 'pixels', 'Position', [115.7000, 65.5000, 73.8000, 35.4000], ...
                  'HorizontalAlignment', 'center');
    
        % Label for 'Upper Bound'
        uicontrol('Parent', quantatiesOfInterestBlock, 'Style', 'text', 'String', 'Upper Bound', ...
                  'Units', 'pixels', 'Position', [235.0000, 65.5000, 73.8000, 35.4000], ...
                  'HorizontalAlignment', 'center');
    
        % Textbox for the lower bound
        dataManager.QOITextHandles(variableIteration, 1) = uicontrol('Parent', quantatiesOfInterestBlock,...
            'Style', 'edit', ...
            'String', num2str(dataManager.QuantatiesOfInterests(variableIteration).crll, '%.2f'), ...
            'Units', 'pixels', ...
            'Position', [99.4000, 45.0000, 98.5000, 30.000]);              % Centered below 'Lower Bound'
    
        % Textbox for the upper bound
        dataManager.QOITextHandles(variableIteration, 2) = uicontrol('Parent', quantatiesOfInterestBlock,...
            'Style', 'edit', ...
            'String', num2str(dataManager.QuantatiesOfInterests(variableIteration).crul, '%.2f'), ...
            'Units', 'pixels', ...
            'Position', [230.0000, 45.0000, 98.5000, 30.000]);             % Centered below 'Upper Bound'
        
        % Label for 'Colour'
        uicontrol('Parent', quantatiesOfInterestBlock, 'Style', 'text', 'String', 'Colour', ...
                  'Units', 'pixels', 'Position', [363.5000, 65.5000, 73.8000, 35.4000], ...
                  'HorizontalAlignment', 'center');
        
        % Add the uicolorpicker with adjusted position
        uicolorpicker('Parent', quantatiesOfInterestBlock, ...
                    'Position', [378.5000, 47.5000, 40.000, 30.000], ...
                    'Value', dataManager.QuantatiesOfInterests(variableIteration).color(1:3), ...
                    ValueChangedFcn=@(src,event) update_color(src, dataManager, variableIteration));
    end

    scroll(quantatiesOfInterestPanel,'top','right')

    %% 3. Update QOI
    uicontrol('Parent', quantatiesOfInterestPanel, 'Style', 'pushbutton', 'String', 'Update QOI Data', ...
              'Units', 'normalized', 'Position', [0.375, 0.035, 0.25, 0.08], ...
              'BackgroundColor', [0.94, 0.94, 0.94], ...
              'Callback', @(src, event) update_qoi_callback(dataManager, nQuantatiesOfInterest));


    %% 4. Tab to display selected values dynamically (for nVars variables) %%
    selectionPanel = uipanel('Parent', tab2, 'Title', 'Selected Values from Plot', ...
                         'Units', 'pixels',...
                         'Position', [14.6000   60.00  516.8000  450.0000], ... %14.4000
                         'Scrollable','on');
    
    % Parameters
    visiblePairs = 7;
    panelHeight = 509.2;
    
    spacePerPair = panelHeight / visiblePairs;
    
    textBoxHeight = 30;
    labelHeight = 20;
    verticalGap = spacePerPair - textBoxHeight;
    horizontalGap = 4;
    labelWidth = 150;
    textBoxWidth = 250;
    leftMargin = 20;
    topMargin = 20;
    bottomMargin = 20;
    
    nTotal = nVariables + numel(dataManager.QuantatiesOfInterests);
    scrollContentHeight = nTotal * spacePerPair + topMargin + bottomMargin;
    
    for selectionIdx = 1:nVariables
        bottom = scrollContentHeight - (topMargin + selectionIdx * spacePerPair);
        
        % Label
        uicontrol('Parent', selectionPanel, 'Style', 'text', ...
            'String', [dataManager.DesignVariables(selectionIdx).dispname ':'], ...
            'Units', 'pixels', ...
            'Position', [leftMargin, bottom + (textBoxHeight - labelHeight)/2, labelWidth, labelHeight], ...
            'HorizontalAlignment', 'left');
        
        % Text box
        dataManager.DataTextHandles(selectionIdx) = uicontrol('Parent', selectionPanel, ...
            'Style', 'edit', 'String', 'N/A', 'Enable', 'off', ...
            'Units', 'pixels', ...
            'Position', [leftMargin + labelWidth + horizontalGap, bottom, textBoxWidth, textBoxHeight]);
    end
    
    for j = 1:numel(dataManager.QuantatiesOfInterests)
        idx = nVariables + j;
        bottom = scrollContentHeight - (topMargin + idx * spacePerPair);
        
        % Label
        uicontrol('Parent', selectionPanel, 'Style', 'text', ...
            'String', [dataManager.QuantatiesOfInterests(j).varname ':'], ...
            'Units', 'pixels', ...
            'Position', [leftMargin, bottom + (textBoxHeight - labelHeight)/2, labelWidth, labelHeight], ...
            'HorizontalAlignment', 'left');
        
        % Text box
        dataManager.DataTextHandles(idx) = uicontrol('Parent', selectionPanel, ...
            'Style', 'edit', 'String', 'N/A', 'Enable', 'off', ...
            'Units', 'pixels', ...
            'Position', [leftMargin + labelWidth + horizontalGap, bottom, textBoxWidth, textBoxHeight]);
    end
    
    % Button stays below visible window
    buttonHeight = 40;
    buttonWidth = 200;
    buttonBottom = 10;
    
    uicontrol('Parent', tab2, 'Style', 'pushbutton', ...
    'String', 'Select Point from Plot', ...
    'Units', 'pixels', ...
    'Position', [(selectionPanel.Position(3) - buttonWidth)/2, buttonBottom, buttonWidth, buttonHeight], ...
    'Callback', @(btn, event) activate_selection_mode(dataManager));

    scroll(selectionPanel,'top','right')

    %% 5. Tab to Create Post-processing Panel %%

    % Create the Post-processing Panel with relative position in the main figure
    postProcessingPanel = uipanel('Parent', tab3, 'Title', 'Post-processing', ...
                                  'Units', 'normalized',...
                                  'Position', [0.015, 0.55, 0.95, 0.4]);
    
    % Text box for Excel file name
    uicontrol('Parent', postProcessingPanel, 'Style', 'text', 'String', 'Excel File Name:', ...
        'Units', 'normalized', 'Position', [0.05, 0.8, 0.5, 0.1], 'HorizontalAlignment', 'left');
    dataManager.PostTextHandles(1) = uicontrol('Parent', postProcessingPanel, 'Style', 'edit', ...
        'Units', 'normalized', 'Position', [0.35, 0.8, 0.45, 0.1]);
    
    % Text box for Figure file name
    uicontrol('Parent', postProcessingPanel, 'Style', 'text', 'String', 'Figure File Name:', ...
        'Units', 'normalized', 'Position', [0.05, 0.6, 0.5, 0.1], 'HorizontalAlignment', 'left');
    dataManager.PostTextHandles(2) = uicontrol('Parent', postProcessingPanel, 'Style', 'edit', ...
        'Units', 'normalized', 'Position', [0.35, 0.6, 0.45, 0.1]);
    
    % Text box for Save Path
    uicontrol('Parent', postProcessingPanel, 'Style', 'text', 'String', 'Save Path:', ...
        'Units', 'normalized', 'Position', [0.05, 0.4, 0.5, 0.1], 'HorizontalAlignment', 'left');
    dataManager.PostTextHandles(3) = uicontrol('Parent', postProcessingPanel, 'Style', 'edit', ...
        'Units', 'normalized', 'Position', [0.35, 0.4, 0.55, 0.1]);
    
    % Save button at the bottom of the GUI
    uicontrol('Parent', postProcessingPanel, 'Style', 'pushbutton',...
        'String', 'Save Figure and Data','Units', 'normalized',...
        'Position', [0.2, 0.1, 0.6, 0.15],...
        'Callback', @(src, event) save_files(src, event, dataManager, hFig));
    
    %% 6. Update Plot button at the bottom of the GUI
    uicontrol('Parent', hFig, 'Style', 'pushbutton', 'String', 'Update Plot', ...
              'Units', 'normalized', 'Position', [0.325, 0.035, 0.2, 0.08], ...
              'Callback', @(src, event) update_plot(dataManager));
    
    %% 7. Rerun the Optimization
    uicontrol('Parent', hFig, 'Style', 'pushbutton', 'String', 'Optimize', ...
              'Units', 'normalized', 'Position', [0.55, 0.035, 0.1, 0.08], ...
              'BackgroundColor', [0.94, 0.94, 0.94], ...
              'Callback', @(src, event) run_optimization(dataManager));

    %% 8. Plot
    % Create the figure box for placing figure
    axisPanel = uipanel('Parent', hFig, 'Title', 'Solution Space', ...
                        'Units', 'pixels', ...
                        'BackgroundColor', [1 1 1], ...
                        'Position', [615.7000, 113.3500, 683.0000, 599.2000],...
                        'Scrollable','on');
    
    scroll(axisPanel,'top','right')

    % Create the Ui Axes for the solution Space
    % Fixed dimensions and spacing
    axWidth  = 153;
    axHeight = 455;
    gap = 55;
    
    % Base offsets (lower-left of first plot)
    initialX = 55;
    initialY = 60;
    
    % Number of plots and layout
    numberPlots = numel(dataManager.DesiredPlots);
    numberColumns = min(3, numberPlots);                                   % Max 3 columns
    numberRows = ceil(numberPlots / numberColumns);                        % Compute rows
    
    % Preallocate axes handles
    dataManager.AxisHandles.IndividualPlots = gobjects(1, numberPlots);
    
    for i = 1:numberPlots
        row = numberRows - floor((i-1) / numberColumns);                   % Top-to-bottom row index
        col = mod(i-1, numberColumns) + 1;                                 % Left-to-right column index
    
        % Compute pixel position for each axis
        posX = initialX + (col - 1) * (axWidth + gap);
        posY = initialY + (row - 1) * (axHeight + gap);
    
        % Create axes
        dataManager.AxisHandles.IndividualPlots(i) = axes('Parent', axisPanel, ...
            'Units', 'pixels', ...
            'Position', [posX, posY, axWidth, axHeight], ...
            'Tag', sprintf('Plot%d', i), ...
            'XLimMode', 'manual', ...
            'YLimMode', 'manual', ...
            'NextPlot', 'replacechildren');
    
        % Disable default tools but keep object interactivity
        axis(dataManager.AxisHandles.IndividualPlots(i), 'manual');
        zoom(dataManager.AxisHandles.IndividualPlots(i), 'off');
        pan(dataManager.AxisHandles.IndividualPlots(i), 'off');
        rotate3d(dataManager.AxisHandles.IndividualPlots(i), 'off');
        set(dataManager.AxisHandles.IndividualPlots(i), ...
            'HitTest', 'on', 'PickableParts', 'all');
    end

    solution_space_plot_axis_patch(dataManager);

end